get_pdf_query = '''
SELECT PS.PATH, DT.ID, DT.EDRPOU, DT.DOCDATE, DT.RECEPTORID, DT.FILENAMEPDF 
FROM BZLOGS.DOCTITLES_PTAH DT
LEFT JOIN BZLOGS.PTAH_SENDER PS ON PS.EDRPOU = DT.EDRPOU 
WHERE DT.FILENAME = :FILENAME
'''